/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/dayu-autostreamer/dayu-sedna/pkg/apis/sedna/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRuntimeServices implements RuntimeServiceInterface
type FakeRuntimeServices struct {
	Fake *FakeSednaV1alpha1
	ns   string
}

var runtimeservicesResource = schema.GroupVersionResource{Group: "sedna.io", Version: "v1alpha1", Resource: "runtimeservices"}

var runtimeservicesKind = schema.GroupVersionKind{Group: "sedna.io", Version: "v1alpha1", Kind: "RuntimeService"}

// Get takes name of the runtimeService, and returns the corresponding runtimeService object, and an error if there is any.
func (c *FakeRuntimeServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RuntimeService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(runtimeservicesResource, c.ns, name), &v1alpha1.RuntimeService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeService), err
}

// List takes label and field selectors, and returns the list of RuntimeServices that match those selectors.
func (c *FakeRuntimeServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RuntimeServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(runtimeservicesResource, runtimeservicesKind, c.ns, opts), &v1alpha1.RuntimeServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RuntimeServiceList{ListMeta: obj.(*v1alpha1.RuntimeServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.RuntimeServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested runtimeServices.
func (c *FakeRuntimeServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(runtimeservicesResource, c.ns, opts))

}

// Create takes the representation of a runtimeService and creates it.  Returns the server's representation of the runtimeService, and an error, if there is any.
func (c *FakeRuntimeServices) Create(ctx context.Context, runtimeService *v1alpha1.RuntimeService, opts v1.CreateOptions) (result *v1alpha1.RuntimeService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(runtimeservicesResource, c.ns, runtimeService), &v1alpha1.RuntimeService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeService), err
}

// Update takes the representation of a runtimeService and updates it. Returns the server's representation of the runtimeService, and an error, if there is any.
func (c *FakeRuntimeServices) Update(ctx context.Context, runtimeService *v1alpha1.RuntimeService, opts v1.UpdateOptions) (result *v1alpha1.RuntimeService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(runtimeservicesResource, c.ns, runtimeService), &v1alpha1.RuntimeService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRuntimeServices) UpdateStatus(ctx context.Context, runtimeService *v1alpha1.RuntimeService, opts v1.UpdateOptions) (*v1alpha1.RuntimeService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(runtimeservicesResource, "status", c.ns, runtimeService), &v1alpha1.RuntimeService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeService), err
}

// Delete takes name of the runtimeService and deletes it. Returns an error if one occurs.
func (c *FakeRuntimeServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(runtimeservicesResource, c.ns, name), &v1alpha1.RuntimeService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRuntimeServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(runtimeservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RuntimeServiceList{})
	return err
}

// Patch applies the patch and returns the patched runtimeService.
func (c *FakeRuntimeServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RuntimeService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(runtimeservicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.RuntimeService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeService), err
}
