# Template of driver-opt parameters for docker buildx create
# Default driver_opts.toml is empty
# If you want to use proxy in docker buildx, please modify driver_opts.toml as the following templates


env.HTTP_PROXY = "http://192.168.3.5:7890"
env.HTTPS_PROXY = "http://192.168.3.5:7890"
env.NO_PROXY = "localhost,127.0.0.1,114.212.87.136,repo"

