/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"
	// TODO: v1alpha1路径问题
	// v1alpha1 "github.com/adayangolzz/sedna-modified/pkg/apis/sedna/v1alpha1"
	// scheme "github.com/adayangolzz/sedna-modified/pkg/client/clientset/versioned/scheme"
	v1alpha1 "github.com/adayangolzz/sedna-modified/pkg/apis/sedna/v1alpha1"
	scheme "github.com/adayangolzz/sedna-modified/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// JointMultiEdgeServicesGetter has a method to return a JointMultiEdgeServiceInterface.
// A group's client should implement this interface.
type JointMultiEdgeServicesGetter interface {
	JointMultiEdgeServices(namespace string) JointMultiEdgeServiceInterface
}

// JointMultiEdgeServiceInterface has methods to work with JointMultiEdgeService resources.
type JointMultiEdgeServiceInterface interface {
	Create(ctx context.Context, jointMultiEdgeService *v1alpha1.JointMultiEdgeService, opts v1.CreateOptions) (*v1alpha1.JointMultiEdgeService, error)
	Update(ctx context.Context, jointMultiEdgeService *v1alpha1.JointMultiEdgeService, opts v1.UpdateOptions) (*v1alpha1.JointMultiEdgeService, error)
	UpdateStatus(ctx context.Context, jointMultiEdgeService *v1alpha1.JointMultiEdgeService, opts v1.UpdateOptions) (*v1alpha1.JointMultiEdgeService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.JointMultiEdgeService, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.JointMultiEdgeServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JointMultiEdgeService, err error)
	JointMultiEdgeServiceExpansion
}

// jointMultiEdgeServices implements JointMultiEdgeServiceInterface
type jointMultiEdgeServices struct {
	client rest.Interface
	ns     string
}

// newJointMultiEdgeServices returns a JointMultiEdgeServices
func newJointMultiEdgeServices(c *SednaV1alpha1Client, namespace string) *jointMultiEdgeServices {
	return &jointMultiEdgeServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the jointMultiEdgeService, and returns the corresponding jointMultiEdgeService object, and an error if there is any.
func (c *jointMultiEdgeServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.JointMultiEdgeService, err error) {
	result = &v1alpha1.JointMultiEdgeService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jointmultiedgeservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of JointMultiEdgeServices that match those selectors.
func (c *jointMultiEdgeServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.JointMultiEdgeServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.JointMultiEdgeServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jointmultiedgeservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested jointMultiEdgeServices.
func (c *jointMultiEdgeServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("jointmultiedgeservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a jointMultiEdgeService and creates it.  Returns the server's representation of the jointMultiEdgeService, and an error, if there is any.
func (c *jointMultiEdgeServices) Create(ctx context.Context, jointMultiEdgeService *v1alpha1.JointMultiEdgeService, opts v1.CreateOptions) (result *v1alpha1.JointMultiEdgeService, err error) {
	result = &v1alpha1.JointMultiEdgeService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("jointmultiedgeservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jointMultiEdgeService).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a jointMultiEdgeService and updates it. Returns the server's representation of the jointMultiEdgeService, and an error, if there is any.
func (c *jointMultiEdgeServices) Update(ctx context.Context, jointMultiEdgeService *v1alpha1.JointMultiEdgeService, opts v1.UpdateOptions) (result *v1alpha1.JointMultiEdgeService, err error) {
	result = &v1alpha1.JointMultiEdgeService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jointmultiedgeservices").
		Name(jointMultiEdgeService.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jointMultiEdgeService).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *jointMultiEdgeServices) UpdateStatus(ctx context.Context, jointMultiEdgeService *v1alpha1.JointMultiEdgeService, opts v1.UpdateOptions) (result *v1alpha1.JointMultiEdgeService, err error) {
	result = &v1alpha1.JointMultiEdgeService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jointmultiedgeservices").
		Name(jointMultiEdgeService.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jointMultiEdgeService).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the jointMultiEdgeService and deletes it. Returns an error if one occurs.
func (c *jointMultiEdgeServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jointmultiedgeservices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *jointMultiEdgeServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jointmultiedgeservices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched jointMultiEdgeService.
func (c *jointMultiEdgeServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JointMultiEdgeService, err error) {
	result = &v1alpha1.JointMultiEdgeService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("jointmultiedgeservices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
