/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/dayu-autostreamer/dayu-sedna/pkg/apis/sedna/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RuntimeServiceLister helps list RuntimeServices.
// All objects returned here must be treated as read-only.
type RuntimeServiceLister interface {
	// List lists all RuntimeServices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RuntimeService, err error)
	// RuntimeServices returns an object that can list and get RuntimeServices.
	RuntimeServices(namespace string) RuntimeServiceNamespaceLister
	RuntimeServiceListerExpansion
}

// runtimeServiceLister implements the RuntimeServiceLister interface.
type runtimeServiceLister struct {
	indexer cache.Indexer
}

// NewRuntimeServiceLister returns a new RuntimeServiceLister.
func NewRuntimeServiceLister(indexer cache.Indexer) RuntimeServiceLister {
	return &runtimeServiceLister{indexer: indexer}
}

// List lists all RuntimeServices in the indexer.
func (s *runtimeServiceLister) List(selector labels.Selector) (ret []*v1alpha1.RuntimeService, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RuntimeService))
	})
	return ret, err
}

// RuntimeServices returns an object that can list and get RuntimeServices.
func (s *runtimeServiceLister) RuntimeServices(namespace string) RuntimeServiceNamespaceLister {
	return runtimeServiceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RuntimeServiceNamespaceLister helps list and get RuntimeServices.
// All objects returned here must be treated as read-only.
type RuntimeServiceNamespaceLister interface {
	// List lists all RuntimeServices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RuntimeService, err error)
	// Get retrieves the RuntimeService from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.RuntimeService, error)
	RuntimeServiceNamespaceListerExpansion
}

// runtimeServiceNamespaceLister implements the RuntimeServiceNamespaceLister
// interface.
type runtimeServiceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RuntimeServices in the indexer for a given namespace.
func (s runtimeServiceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.RuntimeService, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RuntimeService))
	})
	return ret, err
}

// Get retrieves the RuntimeService from the indexer for a given namespace and name.
func (s runtimeServiceNamespaceLister) Get(name string) (*v1alpha1.RuntimeService, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("runtimeservice"), name)
	}
	return obj.(*v1alpha1.RuntimeService), nil
}
